/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import Componentes.Fecha;
import Componentes.Mensajes;
import Componentes.clsExportarExcel;
import Controladores.CabecerasTablas;
import Controladores.controlCliente;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDialog;

/**
 *
 * @author ADMIN
 */
public class dlgExportaciones extends javax.swing.JDialog {

    /**
     * Creates new form dlgExportaciones
     *
     * @param parent
     * @param modal
     */
    public dlgExportaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CabecerasTablas.clienteContaduria(tbClientes);
        CabecerasTablas.actosGravados(tbActosGrabados);
        CabecerasTablas.ventaCabecera(tbVentaCabecera);
        CabecerasTablas.ventaDetalle(tbVentaDetalle);
        controlCliente.listClientesContaduria(tbClientes);
        controlCliente.listActosGravados(tbActosGrabados);
        //txtFechaFiltroD.setVisible(false);
        //txtFechaFiltroH.setVisible(false);
        //txtFechaFiltroD1.setVisible(false);
        //txtFechaFiltroH1.setVisible(false);
        PanelCiente.setFocusable(true);
        
    }

    private void MensajeLabel() {
        DecimalFormat formato = new DecimalFormat("#,###");
        if (PanelCiente.isShowing()) {
            if(tbClientes.getRowCount() <= 0){
                etiMensaje.setText(" SIN REGISTROS.");
            }else{
               etiMensaje.setText("SE HAN CONTABILIZADO " + formato.format(tbClientes.getRowCount()) + " CLIENTES EN LA TABLA."); 
            }            
        }else if (PanelIVA.isShowing()) {
            if(tbActosGrabados.getRowCount() <= 0){
                etiMensaje.setText(" SIN REGISTROS.");
            }else{
               etiMensaje.setText("SE HAN CONTABILIZADO " + formato.format(tbActosGrabados.getRowCount()) + " ACTOS GRAVADOS EN LA TABLA."); 
            }            
        } else if (PanelCabecera.isShowing()) {
            if (tbVentaCabecera.getRowCount() <= 0) {
                etiMensaje.setText(" SIN COINCIDENCIAS.");
            }else if(tbVentaCabecera.getRowCount() == 1){
                etiMensaje.setText("SE HA CONTABILIZADO " + tbVentaCabecera.getRowCount() + " VENTA CABECERA EN LA TABLA.");
            }else {
                etiMensaje.setText("SE HAN CONTABILIZADO " + formato.format(tbVentaCabecera.getRowCount()) + " VENTAS CABECERAS EN LA TABLA.");
            }
        } else if (PanelDetalle.isShowing()) {
            if (tbVentaDetalle.getRowCount() <= 0) {
                etiMensaje.setText(" SIN COINCIDENCIAS.");
            }else if (tbVentaDetalle.getRowCount() == 1) {
                etiMensaje.setText("SE HA CONTABILIZADO " + tbVentaDetalle.getRowCount() + " VENTA DETALLE EN LA TABLA.");
            } else {
                etiMensaje.setText("SE HAN CONTABILIZADO " + formato.format(tbVentaDetalle.getRowCount()) + " VENTAS DETALLES EN LA TABLA.");
            }
        } else {
            etiMensaje.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelCiente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        btnExportar = new newscomponents.RSButtonBigIcon_new();
        PanelIVA = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbActosGrabados = new javax.swing.JTable();
        btnExportar3 = new newscomponents.RSButtonBigIcon_new();
        PanelCabecera = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbVentaCabecera = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaD = new javax.swing.JTextField();
        dcFechaD = new datechooser.beans.DateChooserCombo();
        txtFechaH = new javax.swing.JTextField();
        dcFechaH = new datechooser.beans.DateChooserCombo();
        txtFechaFiltroH = new javax.swing.JTextField();
        txtFechaFiltroD = new javax.swing.JTextField();
        btnFiltrar4 = new newscomponents.RSButtonBigIcon_new();
        btnExportar1 = new newscomponents.RSButtonBigIcon_new();
        PanelDetalle = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbVentaDetalle = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFechaD1 = new javax.swing.JTextField();
        dcFechaD1 = new datechooser.beans.DateChooserCombo();
        txtFechaH1 = new javax.swing.JTextField();
        dcFechaH1 = new datechooser.beans.DateChooserCombo();
        txtFechaFiltroH1 = new javax.swing.JTextField();
        txtFechaFiltroD1 = new javax.swing.JTextField();
        btnFiltrar3 = new newscomponents.RSButtonBigIcon_new();
        btnExportar2 = new newscomponents.RSButtonBigIcon_new();
        jPanel1 = new javax.swing.JPanel();
        btnSalir1 = new newscomponents.RSButtonBigIcon_new();
        jLabel5 = new javax.swing.JLabel();
        etiMensaje = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jTabbedPane1.setBackground(new java.awt.Color(17, 35, 46));
        jTabbedPane1.setForeground(new java.awt.Color(17, 35, 46));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        PanelCiente.setBackground(new java.awt.Color(255, 255, 255));
        PanelCiente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PanelCienteFocusLost(evt);
            }
        });
        PanelCiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelCienteMousePressed(evt);
            }
        });
        PanelCiente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tbClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbClientes.setEnabled(false);
        tbClientes.setGridColor(new java.awt.Color(224, 224, 224));
        tbClientes.setRowHeight(18);
        tbClientes.setShowGrid(false);
        tbClientes.setShowHorizontalLines(true);
        tbClientes.getTableHeader().setResizingAllowed(false);
        tbClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbClientes);

        PanelCiente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1117, 560));

        btnExportar.setBackground(new java.awt.Color(255, 255, 255));
        btnExportar.setBorder(null);
        btnExportar.setForeground(new java.awt.Color(0, 0, 0));
        btnExportar.setText("DESCARGAR INFORMACIÓN");
        btnExportar.setBgHover(new java.awt.Color(255, 255, 255));
        btnExportar.setFgHover(new java.awt.Color(102, 102, 102));
        btnExportar.setFgIcon(new java.awt.Color(17, 35, 46));
        btnExportar.setFgIconHover(new java.awt.Color(102, 102, 102));
        btnExportar.setFgText(new java.awt.Color(17, 35, 46));
        btnExportar.setFocusPainted(false);
        btnExportar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnExportar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnExportar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnExportar.setIconTextGap(0);
        btnExportar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILE_DOWNLOAD);
        btnExportar.setPixels(0);
        btnExportar.setSizeIcon(30.0F);
        btnExportar.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        PanelCiente.add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 213, 30));

        jTabbedPane1.addTab("CLIENTES              ", new javax.swing.ImageIcon(getClass().getResource("/Iconos/mimetypes_excel.png")), PanelCiente); // NOI18N

        PanelIVA.setBackground(new java.awt.Color(255, 255, 255));
        PanelIVA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tbActosGrabados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbActosGrabados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbActosGrabados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbActosGrabados.setEnabled(false);
        tbActosGrabados.setGridColor(new java.awt.Color(224, 224, 224));
        tbActosGrabados.setRowHeight(18);
        tbActosGrabados.setShowGrid(false);
        tbActosGrabados.setShowHorizontalLines(true);
        tbActosGrabados.getTableHeader().setResizingAllowed(false);
        tbActosGrabados.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tbActosGrabados);

        PanelIVA.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1117, 560));

        btnExportar3.setBackground(new java.awt.Color(255, 255, 255));
        btnExportar3.setBorder(null);
        btnExportar3.setForeground(new java.awt.Color(0, 0, 0));
        btnExportar3.setText("DESCARGAR INFORMACIÓN");
        btnExportar3.setBgHover(new java.awt.Color(255, 255, 255));
        btnExportar3.setFgHover(new java.awt.Color(102, 102, 102));
        btnExportar3.setFgIcon(new java.awt.Color(39, 61, 75));
        btnExportar3.setFgIconHover(new java.awt.Color(102, 102, 102));
        btnExportar3.setFgText(new java.awt.Color(0, 0, 0));
        btnExportar3.setFocusPainted(false);
        btnExportar3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnExportar3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnExportar3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnExportar3.setIconTextGap(0);
        btnExportar3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILE_DOWNLOAD);
        btnExportar3.setPixels(0);
        btnExportar3.setSizeIcon(30.0F);
        btnExportar3.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportar3ActionPerformed(evt);
            }
        });
        PanelIVA.add(btnExportar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 213, 30));

        jTabbedPane1.addTab("ACTOS GRAVADOS", new javax.swing.ImageIcon(getClass().getResource("/Iconos/mimetypes_excel.png")), PanelIVA); // NOI18N

        PanelCabecera.setBackground(new java.awt.Color(255, 255, 255));
        PanelCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tbVentaCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbVentaCabecera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TIMBRADO", "REGIMEN", "FECHA", "NRO_FAC", "ID_TIPDOCU", "ID_CLIENTE", "ID_MONEDA"
            }
        ));
        tbVentaCabecera.setEnabled(false);
        tbVentaCabecera.setGridColor(new java.awt.Color(219, 219, 219));
        tbVentaCabecera.setRowHeight(18);
        tbVentaCabecera.setShowVerticalLines(false);
        tbVentaCabecera.getTableHeader().setResizingAllowed(false);
        tbVentaCabecera.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbVentaCabecera);

        PanelCabecera.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 1117, 520));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("Fecha desde");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1, -1, 29));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setText("Fecha hasta");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 1, -1, 29));

        txtFechaD.setEditable(false);
        txtFechaD.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaD.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        txtFechaD.setForeground(new java.awt.Color(17, 35, 46));
        txtFechaD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(txtFechaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 1, 130, 29));

        dcFechaD.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dcFechaD.setCalendarBackground(new java.awt.Color(255, 255, 255));
    dcFechaD.setFieldFont(new java.awt.Font("Roboto Black", java.awt.Font.BOLD, 15));
    dcFechaD.setNavigateFont(new java.awt.Font("Roboto", java.awt.Font.PLAIN, 11));
    dcFechaD.setShowOneMonth(true);
    dcFechaD.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            dcFechaDOnCommit(evt);
        }
    });
    jPanel2.add(dcFechaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 1, 27, 29));

    txtFechaH.setEditable(false);
    txtFechaH.setBackground(new java.awt.Color(255, 255, 255));
    txtFechaH.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
    txtFechaH.setForeground(new java.awt.Color(17, 35, 46));
    txtFechaH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtFechaH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    jPanel2.add(txtFechaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 1, 130, 29));

    dcFechaH.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
dcFechaH.setCalendarBackground(new java.awt.Color(255, 255, 255));
dcFechaH.setFieldFont(new java.awt.Font("Roboto Black", java.awt.Font.BOLD, 15));
dcFechaH.setNavigateFont(new java.awt.Font("Roboto", java.awt.Font.PLAIN, 11));
dcFechaH.setShowOneMonth(true);
dcFechaH.addCommitListener(new datechooser.events.CommitListener() {
    public void onCommit(datechooser.events.CommitEvent evt) {
        dcFechaHOnCommit(evt);
    }
    });
    jPanel2.add(dcFechaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 1, 27, 29));
    jPanel2.add(txtFechaFiltroH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1004, 1, 89, -1));
    jPanel2.add(txtFechaFiltroD, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 1, 76, -1));

    btnFiltrar4.setBackground(new java.awt.Color(17, 35, 46));
    btnFiltrar4.setBorder(null);
    btnFiltrar4.setText("BUSCAR COINCIDENCIAS");
    btnFiltrar4.setBgHover(new java.awt.Color(39, 61, 75));
    btnFiltrar4.setFocusPainted(false);
    btnFiltrar4.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
    btnFiltrar4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnFiltrar4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    btnFiltrar4.setIconTextGap(0);
    btnFiltrar4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
    btnFiltrar4.setPixels(0);
    btnFiltrar4.setSizeIcon(25.0F);
    btnFiltrar4.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
    btnFiltrar4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnFiltrar4ActionPerformed(evt);
        }
    });
    jPanel2.add(btnFiltrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 1, 165, 29));

    PanelCabecera.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 1094, 31));

    btnExportar1.setBackground(new java.awt.Color(255, 255, 255));
    btnExportar1.setBorder(null);
    btnExportar1.setForeground(new java.awt.Color(0, 0, 0));
    btnExportar1.setText("DESCARGAR INFORMACIÓN");
    btnExportar1.setBgHover(new java.awt.Color(255, 255, 255));
    btnExportar1.setFgHover(new java.awt.Color(102, 102, 102));
    btnExportar1.setFgIcon(new java.awt.Color(17, 35, 46));
    btnExportar1.setFgIconHover(new java.awt.Color(102, 102, 102));
    btnExportar1.setFgText(new java.awt.Color(17, 35, 46));
    btnExportar1.setFocusPainted(false);
    btnExportar1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    btnExportar1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    btnExportar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    btnExportar1.setIconTextGap(0);
    btnExportar1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILE_DOWNLOAD);
    btnExportar1.setPixels(0);
    btnExportar1.setSizeIcon(30.0F);
    btnExportar1.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
    btnExportar1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnExportar1ActionPerformed(evt);
        }
    });
    PanelCabecera.add(btnExportar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 213, 30));

    jTabbedPane1.addTab("VENTA CABECERA", new javax.swing.ImageIcon(getClass().getResource("/Iconos/mimetypes_excel.png")), PanelCabecera); // NOI18N

    PanelDetalle.setBackground(new java.awt.Color(255, 255, 255));
    PanelDetalle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

    tbVentaDetalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    tbVentaDetalle.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null, null, null, null}
        },
        new String [] {
            "TIMBRADO", "REGIMEN", "FECHA", "NRO_FAC", "ID_TIPDOCU", "ID_CLIENTE", "ID_ACTOS", "FORMA_IMP", "IMPORTE", "PDESCUENTO", "PDESCUENTODE"
        }
    ));
    tbVentaDetalle.setEnabled(false);
    tbVentaDetalle.setGridColor(new java.awt.Color(216, 216, 216));
    tbVentaDetalle.setRowHeight(18);
    tbVentaDetalle.setShowGrid(false);
    tbVentaDetalle.setShowHorizontalLines(true);
    tbVentaDetalle.getTableHeader().setResizingAllowed(false);
    tbVentaDetalle.getTableHeader().setReorderingAllowed(false);
    jScrollPane3.setViewportView(tbVentaDetalle);

    PanelDetalle.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 1117, 520));

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));
    jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    jLabel6.setText("Fecha desde");
    jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 1, -1, 29));

    jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    jLabel7.setText("Fecha hasta");
    jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 1, -1, 29));

    txtFechaD1.setEditable(false);
    txtFechaD1.setBackground(new java.awt.Color(255, 255, 255));
    txtFechaD1.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
    txtFechaD1.setForeground(new java.awt.Color(17, 35, 46));
    txtFechaD1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtFechaD1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    jPanel3.add(txtFechaD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 1, 130, 29));

    dcFechaD1.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
dcFechaD1.setCalendarBackground(new java.awt.Color(255, 255, 255));
dcFechaD1.setFieldFont(new java.awt.Font("Roboto Black", java.awt.Font.BOLD, 15));
dcFechaD1.setNavigateFont(new java.awt.Font("Roboto", java.awt.Font.PLAIN, 11));
dcFechaD1.setShowOneMonth(true);
dcFechaD1.addCommitListener(new datechooser.events.CommitListener() {
    public void onCommit(datechooser.events.CommitEvent evt) {
        dcFechaD1OnCommit(evt);
    }
    });
    jPanel3.add(dcFechaD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 1, 27, 29));

    txtFechaH1.setEditable(false);
    txtFechaH1.setBackground(new java.awt.Color(255, 255, 255));
    txtFechaH1.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
    txtFechaH1.setForeground(new java.awt.Color(17, 35, 46));
    txtFechaH1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtFechaH1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    txtFechaH1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtFechaH1ActionPerformed(evt);
        }
    });
    jPanel3.add(txtFechaH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 1, 130, 29));

    dcFechaH1.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
dcFechaH1.setCalendarBackground(new java.awt.Color(255, 255, 255));
dcFechaH1.setFieldFont(new java.awt.Font("Roboto Black", java.awt.Font.BOLD, 15));
dcFechaH1.setNavigateFont(new java.awt.Font("Roboto", java.awt.Font.PLAIN, 11));
dcFechaH1.setShowOneMonth(true);
dcFechaH1.addCommitListener(new datechooser.events.CommitListener() {
    public void onCommit(datechooser.events.CommitEvent evt) {
        dcFechaH1OnCommit(evt);
    }
    });
    jPanel3.add(dcFechaH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 1, 27, 29));
    jPanel3.add(txtFechaFiltroH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1004, 5, 89, -1));
    jPanel3.add(txtFechaFiltroD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 5, 76, -1));

    btnFiltrar3.setBackground(new java.awt.Color(17, 35, 46));
    btnFiltrar3.setBorder(null);
    btnFiltrar3.setText("BUSCAR COINCIDENCIAS");
    btnFiltrar3.setBgHover(new java.awt.Color(39, 61, 75));
    btnFiltrar3.setFocusPainted(false);
    btnFiltrar3.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
    btnFiltrar3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnFiltrar3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    btnFiltrar3.setIconTextGap(0);
    btnFiltrar3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
    btnFiltrar3.setPixels(0);
    btnFiltrar3.setSizeIcon(25.0F);
    btnFiltrar3.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
    btnFiltrar3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnFiltrar3ActionPerformed(evt);
        }
    });
    jPanel3.add(btnFiltrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 1, 165, 29));

    PanelDetalle.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 1094, -1));

    btnExportar2.setBackground(new java.awt.Color(255, 255, 255));
    btnExportar2.setBorder(null);
    btnExportar2.setForeground(new java.awt.Color(0, 0, 0));
    btnExportar2.setText("DESCARGAR INFORMACIÓN");
    btnExportar2.setBgHover(new java.awt.Color(255, 255, 255));
    btnExportar2.setFgHover(new java.awt.Color(102, 102, 102));
    btnExportar2.setFgIcon(new java.awt.Color(17, 35, 46));
    btnExportar2.setFgIconHover(new java.awt.Color(102, 102, 102));
    btnExportar2.setFgText(new java.awt.Color(17, 35, 46));
    btnExportar2.setFocusPainted(false);
    btnExportar2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    btnExportar2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    btnExportar2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    btnExportar2.setIconTextGap(0);
    btnExportar2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILE_DOWNLOAD);
    btnExportar2.setPixels(0);
    btnExportar2.setSizeIcon(30.0F);
    btnExportar2.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
    btnExportar2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnExportar2ActionPerformed(evt);
        }
    });
    PanelDetalle.add(btnExportar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 213, 30));

    jTabbedPane1.addTab("VENTA DETALLE   ", new javax.swing.ImageIcon(getClass().getResource("/Iconos/mimetypes_excel.png")), PanelDetalle); // NOI18N

    jPanel1.setBackground(new java.awt.Color(17, 35, 46));

    btnSalir1.setBackground(new java.awt.Color(17, 35, 46));
    btnSalir1.setBorder(null);
    btnSalir1.setBgHover(new java.awt.Color(255, 0, 0));
    btnSalir1.setFocusPainted(false);
    btnSalir1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
    btnSalir1.setIconTextGap(0);
    btnSalir1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
    btnSalir1.setPixels(0);
    btnSalir1.setSizeIcon(20.0F);
    btnSalir1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSalir1ActionPerformed(evt);
        }
    });

    jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("FORMULARIO DE VISUALIZACIÓN Y EXPORTACIÓN DE DATOS PARA CONTABILIDAD");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1263, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel5)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(5, 5, 5))
    );

    etiMensaje.setBackground(new java.awt.Color(51, 51, 51));
    etiMensaje.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
    etiMensaje.setForeground(new java.awt.Color(255, 255, 255));
    etiMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiMensaje.setText("jLabel6");
    etiMensaje.setOpaque(true);

    jLabel3.setBackground(new java.awt.Color(17, 35, 46));
    jLabel3.setOpaque(true);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jTabbedPane1)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(etiMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(etiMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    jTabbedPane1.getAccessibleContext().setAccessibleName("export");

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        try {
            clsExportarExcel Export = new clsExportarExcel();
            Export.exportarExcelClientes(tbClientes, this);
        } catch (IOException ex) {
            //Logger.getLogger(dlgClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void dcFechaDOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dcFechaDOnCommit
        // TODO add your handling code here:
        //txtFecha.setText(InicializarFecha());
        String fe = dcFechaD.getText();
        txtFechaD.setText(Fecha.formatoFechaVM(fe));
        txtFechaFiltroD.setText(Fecha.formatoFechaVMR(fe));
    }//GEN-LAST:event_dcFechaDOnCommit

    private void dcFechaHOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dcFechaHOnCommit
        // TODO add your handling code here:
        String fe = dcFechaH.getText();
        txtFechaH.setText(Fecha.formatoFechaVM(fe));
        txtFechaFiltroH.setText(Fecha.formatoFechaVMR(fe));
    }//GEN-LAST:event_dcFechaHOnCommit

    private void btnExportar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportar1ActionPerformed
        // TODO add your handling code here:
        if(tbVentaCabecera.getRowCount()<=0){
            Mensajes.informacion("La tabla de registros se encuentra vacía.\nVerifique si las fechas (Desde/Hasta) son correctos.");
        }else{
            try {
                clsExportarExcel Export = new clsExportarExcel();
                Export.exportarExcelVentaCabecera(tbVentaCabecera, this);
            } catch (IOException ex) {
                //Logger.getLogger(dlgClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnExportar1ActionPerformed

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        // TODO add your handling code here:
        MensajeLabel();
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void PanelCienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelCienteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelCienteFocusLost

    private void dcFechaD1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dcFechaD1OnCommit
        // TODO add your handling code here:
        String fe = dcFechaD1.getText();
        txtFechaD1.setText(Fecha.formatoFechaVM(fe));
        txtFechaFiltroD1.setText(Fecha.formatoFechaVMR(fe));
    }//GEN-LAST:event_dcFechaD1OnCommit

    private void dcFechaH1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dcFechaH1OnCommit
        // TODO add your handling code here:
        String fe = dcFechaH1.getText();
        txtFechaH1.setText(Fecha.formatoFechaVM(fe));
        txtFechaFiltroH1.setText(Fecha.formatoFechaVMR(fe));
    }//GEN-LAST:event_dcFechaH1OnCommit

    private void btnExportar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportar2ActionPerformed
        // TODO add your handling code here:
        if(tbVentaDetalle.getRowCount()<=0){
            Mensajes.informacion("La tabla de registros se encuentra vacía.\nVerifique si las fechas (Desde/Hasta) son correctos.");
        }else{
            try {
                clsExportarExcel Export = new clsExportarExcel();
                Export.exportarExcelVentaDetalle(tbVentaDetalle, this);
            } catch (IOException ex) {
                //Logger.getLogger(dlgClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnExportar2ActionPerformed

    private void PanelCienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCienteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelCienteMousePressed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
        int rpta = Mensajes.confirmar("¿Seguro que desea salir del formulario?");
        if (rpta == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnExportar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportar3ActionPerformed
        // TODO add your handling code here:
        try {
            clsExportarExcel Export = new clsExportarExcel();
            Export.exportarExcelActosGravados(tbActosGrabados, this);
        } catch (IOException ex) {
            //Logger.getLogger(dlgClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExportar3ActionPerformed

    private void btnFiltrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrar3ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat myFecha = new SimpleDateFormat("yyyy/MM/dd");
        Date desde = null;
        Date hasta = null;
        try {
            desde = myFecha.parse(txtFechaFiltroD1.getText().trim());
            hasta = myFecha.parse(txtFechaFiltroH1.getText().trim());
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        if (txtFechaD1.getText().trim().isEmpty()) {
            Mensajes.informacion("Seleccione la \"Fecha desde\".");
        } else if (txtFechaH1.getText().trim().isEmpty()) {
            Mensajes.informacion("Seleccione la \"Fecha hasta\".");
        } else if (desde.after(hasta)) {
            Mensajes.informacion("La \"Fecha desde\" no puede ser posterior a la \"Fecha hasta\".");
        } else {
            CabecerasTablas.limpiarTablasVentaDetalle(tbVentaDetalle);
            controlCliente.listVDContaduria(tbVentaDetalle, txtFechaFiltroD1.getText().trim(), txtFechaFiltroH1.getText().trim());
            MensajeLabel();
        }
    }//GEN-LAST:event_btnFiltrar3ActionPerformed

    private void btnFiltrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrar4ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat myFecha = new SimpleDateFormat("yyyy/MM/dd");
        Date desde = null;
        Date hasta = null;
        try {
            desde = myFecha.parse(txtFechaFiltroD.getText().trim());
            hasta = myFecha.parse(txtFechaFiltroH.getText().trim());
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        if (txtFechaD.getText().trim().isEmpty()) {
            Mensajes.informacion("Seleccione la \"Fecha desde\".");
        } else if (txtFechaH.getText().trim().isEmpty()) {
            Mensajes.informacion("Seleccione la \"Fecha hasta\".");
        } else if (desde.after(hasta)) {
            Mensajes.informacion("La \"Fecha desde\" no puede ser posterior a la \"Fecha hasta\".");
        } else {
            CabecerasTablas.limpiarTablasVentaCabecera(tbVentaCabecera);
            controlCliente.listVCContaduria(tbVentaCabecera, txtFechaFiltroD.getText().trim(), txtFechaFiltroH.getText().trim());
            MensajeLabel();
        }
    }//GEN-LAST:event_btnFiltrar4ActionPerformed

    private void txtFechaH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaH1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgExportaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgExportaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgExportaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgExportaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgExportaciones dialog = new dlgExportaciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCabecera;
    private javax.swing.JPanel PanelCiente;
    private javax.swing.JPanel PanelDetalle;
    private javax.swing.JPanel PanelIVA;
    public static newscomponents.RSButtonBigIcon_new btnExportar;
    public static newscomponents.RSButtonBigIcon_new btnExportar1;
    public static newscomponents.RSButtonBigIcon_new btnExportar2;
    public static newscomponents.RSButtonBigIcon_new btnExportar3;
    public static newscomponents.RSButtonBigIcon_new btnFiltrar3;
    public static newscomponents.RSButtonBigIcon_new btnFiltrar4;
    public static newscomponents.RSButtonBigIcon_new btnSalir1;
    public static datechooser.beans.DateChooserCombo dcFechaD;
    public static datechooser.beans.DateChooserCombo dcFechaD1;
    public static datechooser.beans.DateChooserCombo dcFechaH;
    public static datechooser.beans.DateChooserCombo dcFechaH1;
    private javax.swing.JLabel etiMensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbActosGrabados;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTable tbVentaCabecera;
    private javax.swing.JTable tbVentaDetalle;
    public static javax.swing.JTextField txtFechaD;
    public static javax.swing.JTextField txtFechaD1;
    private javax.swing.JTextField txtFechaFiltroD;
    private javax.swing.JTextField txtFechaFiltroD1;
    private javax.swing.JTextField txtFechaFiltroH;
    private javax.swing.JTextField txtFechaFiltroH1;
    public static javax.swing.JTextField txtFechaH;
    public static javax.swing.JTextField txtFechaH1;
    // End of variables declaration//GEN-END:variables
}
